flyway.url=jdbc:sqlserver://localhost:1433;databaseName=ebook_store;encrypt=false;trustServerCertificate=true
flyway.user=sa
flyway.password=123456
flyway.locations=filesystem:src/main/resources/db/migration
